local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true

      update_frequency: 10.0
      publish_frequency: 10.0

      width: 20.0
      height: 20.0
      resolution: 0.1

      plugins: ["obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: ["lidar"]
        lidar:
          topic: "/point_cloud"
          data_type: "PointCloud2"
          sensor_frame: "lidar_mount_link"
          marking: true
          clearing: true
          max_obstacle_height: 2.0
          obstacle_range: 5.0
          raytrace_range: 6.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.5

