controller_server:
  ros__parameters:
    controller_frequency: 10.0
    use_sim_time: true

    controller_plugins: ["RPP"]

    RPP:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"

      desired_linear_vel: 0.6
      max_angular_accel: 2.5
      lookahead_dist: 1.0
      min_lookahead_dist: 0.3
      use_velocity_scaled_lookahead_dist: true
      allow_reversing: true
      use_regulated_linear_velocity_scaling: true
      use_cost_regulated_linear_velocity_scaling: true
      inflation_cost_scaling_factor: 3.0
      max_robot_pose_search_dist: 10.0
